# TCL File Generated by Component Editor 16.1
# Fri May 26 22:34:39 GMT+03:00 2017
# DO NOT MODIFY


# 
# console_out "console_out" v1.0
#  2017.05.26.22:34:39
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module console_out
# 
set_module_property DESCRIPTION ""
set_module_property NAME console_out
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME console_out
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL console_out
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file console_out.vhd VHDL PATH periph/console_out.vhd TOP_LEVEL_FILE
add_fileset_file utils.vhd VHDL PATH sorcerer/utils.vhd
add_fileset_file config.vhd VHDL PATH sorcerer/config.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL console_out
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file console_out.vhd VHDL PATH periph/console_out.vhd
add_fileset_file config.vhd VHDL PATH sorcerer/config.vhd
add_fileset_file utils.vhd VHDL PATH sorcerer/utils.vhd


# 
# parameters
# 
add_parameter ROW_NUM NATURAL 34
set_parameter_property ROW_NUM DEFAULT_VALUE 34
set_parameter_property ROW_NUM DISPLAY_NAME ROW_NUM
set_parameter_property ROW_NUM TYPE NATURAL
set_parameter_property ROW_NUM UNITS None
set_parameter_property ROW_NUM ALLOWED_RANGES 0:2147483647
set_parameter_property ROW_NUM HDL_PARAMETER true
add_parameter COL_NUM NATURAL 80
set_parameter_property COL_NUM DEFAULT_VALUE 80
set_parameter_property COL_NUM DISPLAY_NAME COL_NUM
set_parameter_property COL_NUM TYPE NATURAL
set_parameter_property COL_NUM UNITS None
set_parameter_property COL_NUM ALLOWED_RANGES 0:2147483647
set_parameter_property COL_NUM HDL_PARAMETER true
add_parameter BLINKED_CURSOR INTEGER 1
set_parameter_property BLINKED_CURSOR DEFAULT_VALUE 1
set_parameter_property BLINKED_CURSOR DISPLAY_NAME BLINKED_CURSOR
set_parameter_property BLINKED_CURSOR TYPE INTEGER
set_parameter_property BLINKED_CURSOR UNITS None
set_parameter_property BLINKED_CURSOR HDL_PARAMETER true


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock ""
set_interface_property reset synchronousEdges NONE
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point s1
# 
add_interface s1 avalon end
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock clock
set_interface_property s1 associatedReset reset
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 maximumPendingWriteTransactions 0
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true
set_interface_property s1 EXPORT_OF ""
set_interface_property s1 PORT_NAME_MAP ""
set_interface_property s1 CMSIS_SVD_VARIABLES ""
set_interface_property s1 SVD_ADDRESS_GROUP ""

add_interface_port s1 avs_s1_chipselect chipselect Input 1
add_interface_port s1 avs_s1_read read Input 1
add_interface_port s1 avs_s1_write write Input 1
add_interface_port s1 avs_s1_writedata writedata Input 8
add_interface_port s1 avs_s1_readdata readdata Output 8
set_interface_assignment s1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point ext
# 
add_interface ext conduit end
set_interface_property ext associatedClock clock
set_interface_property ext associatedReset reset
set_interface_property ext ENABLED true
set_interface_property ext EXPORT_OF ""
set_interface_property ext PORT_NAME_MAP ""
set_interface_property ext CMSIS_SVD_VARIABLES ""
set_interface_property ext SVD_ADDRESS_GROUP ""

add_interface_port ext HSYNC hsync Output 1
add_interface_port ext VSYNC vsync Output 1
add_interface_port ext BLUE blue Output 8
add_interface_port ext GREEN green Output 8
add_interface_port ext RAMDAC_CLK ramdac_clk Output 1
add_interface_port ext RED red Output 8
add_interface_port ext nRAMDAC_BLANK nramdac_blank Output 1
add_interface_port ext nRAMDAC_SYNC nramdac_sync Output 1

