# TCL File Generated by Component Editor 16.1
# Tue Sep 26 02:58:05 GMT+03:00 2017
# DO NOT MODIFY


# 
# dbg_module_avalon "Debug Module" v1.0
#  2017.09.26.02:58:05
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module dbg_module_avalon
# 
set_module_property DESCRIPTION ""
set_module_property NAME dbg_module_avalon
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Debug Module"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL dbg_module_avalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file dbg_module_avalon.vhd VHDL PATH sorcerer/dbg_module_avalon.vhd TOP_LEVEL_FILE
add_fileset_file config.vhd VHDL PATH sorcerer/config.vhd
add_fileset_file utils.vhd VHDL PATH sorcerer/utils.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL dbg_module_avalon
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file dbg_module_avalon.vhd VHDL PATH sorcerer/dbg_module_avalon.vhd
add_fileset_file config.vhd VHDL PATH sorcerer/config.vhd
add_fileset_file utils.vhd VHDL PATH sorcerer/utils.vhd


# 
# parameters
# 
add_parameter ROM_INIT_FILE STRING ""
set_parameter_property ROM_INIT_FILE DEFAULT_VALUE ""
set_parameter_property ROM_INIT_FILE DISPLAY_NAME ROM_INIT_FILE
set_parameter_property ROM_INIT_FILE TYPE STRING
set_parameter_property ROM_INIT_FILE UNITS None
set_parameter_property ROM_INIT_FILE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point s1
# 
add_interface s1 avalon end
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock clock
set_interface_property s1 associatedReset reset
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 maximumPendingWriteTransactions 0
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true
set_interface_property s1 EXPORT_OF ""
set_interface_property s1 PORT_NAME_MAP ""
set_interface_property s1 CMSIS_SVD_VARIABLES ""
set_interface_property s1 SVD_ADDRESS_GROUP ""

add_interface_port s1 avs_s1_address address Input 10
add_interface_port s1 avs_s1_writedata writedata Input 32
add_interface_port s1 avs_s1_chipselect chipselect Input 1
add_interface_port s1 avs_s1_read read Input 1
add_interface_port s1 avs_s1_write write Input 1
add_interface_port s1 avs_s1_byteenable byteenable Input 4
add_interface_port s1 avs_s1_readdata readdata Output 32
add_interface_port s1 avs_s1_waitrequest waitrequest Output 1
set_interface_assignment s1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point dbg_irq0
# 
add_interface dbg_irq0 conduit end
set_interface_property dbg_irq0 associatedClock clock
set_interface_property dbg_irq0 associatedReset ""
set_interface_property dbg_irq0 ENABLED true
set_interface_property dbg_irq0 EXPORT_OF ""
set_interface_property dbg_irq0 PORT_NAME_MAP ""
set_interface_property dbg_irq0 CMSIS_SVD_VARIABLES ""
set_interface_property dbg_irq0 SVD_ADDRESS_GROUP ""

add_interface_port dbg_irq0 dbg_irq0 irq Output 1


# 
# connection point dbg_set0
# 
add_interface dbg_set0 conduit end
set_interface_property dbg_set0 associatedClock clock
set_interface_property dbg_set0 associatedReset ""
set_interface_property dbg_set0 ENABLED true
set_interface_property dbg_set0 EXPORT_OF ""
set_interface_property dbg_set0 PORT_NAME_MAP ""
set_interface_property dbg_set0 CMSIS_SVD_VARIABLES ""
set_interface_property dbg_set0 SVD_ADDRESS_GROUP ""

add_interface_port dbg_set0 dbg_set0 export Input 1


# 
# connection point halt0
# 
add_interface halt0 conduit end
set_interface_property halt0 associatedClock clock
set_interface_property halt0 associatedReset ""
set_interface_property halt0 ENABLED true
set_interface_property halt0 EXPORT_OF ""
set_interface_property halt0 PORT_NAME_MAP ""
set_interface_property halt0 CMSIS_SVD_VARIABLES ""
set_interface_property halt0 SVD_ADDRESS_GROUP ""

add_interface_port halt0 halt0 export Output 1


# 
# connection point ndreset
# 
add_interface ndreset conduit end
set_interface_property ndreset associatedClock clock
set_interface_property ndreset associatedReset ""
set_interface_property ndreset ENABLED true
set_interface_property ndreset EXPORT_OF ""
set_interface_property ndreset PORT_NAME_MAP ""
set_interface_property ndreset CMSIS_SVD_VARIABLES ""
set_interface_property ndreset SVD_ADDRESS_GROUP ""

add_interface_port ndreset ndreset export Input 1

