# TCL File Generated by Component Editor 16.1
# Tue Sep 26 03:05:03 GMT+03:00 2017
# DO NOT MODIFY


# 
# jtag_transport "JTAG Transport" v1.0
#  2017.09.26.03:05:03
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module jtag_transport
# 
set_module_property DESCRIPTION ""
set_module_property NAME jtag_transport
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "JTAG Transport"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL dbg_jtag_avalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file config.vhd VHDL PATH sorcerer/config.vhd
add_fileset_file dbg_avalon_bridge.vhd VHDL PATH sorcerer/dbg_avalon_bridge.vhd
add_fileset_file dbg_crc.vhd VHDL PATH sorcerer/dbg_crc.vhd
add_fileset_file dbg_jtag_avalon.vhd VHDL PATH sorcerer/dbg_jtag_avalon.vhd TOP_LEVEL_FILE
add_fileset_file dbg_jtag_transport.vhd VHDL PATH sorcerer/dbg_jtag_transport.vhd
add_fileset_file dbg_vjtag.vhd VHDL PATH sorcerer/dbg_vjtag.vhd
add_fileset_file iface.vhd VHDL PATH sorcerer/iface.vhd
add_fileset_file pipeline_iface.vhd VHDL PATH sorcerer/pipeline_iface.vhd
add_fileset_file utils.vhd VHDL PATH sorcerer/utils.vhd
add_fileset_file csr.vhd VHDL PATH sorcerer/csr.vhd
add_fileset_file cache_utils.vhd VHDL PATH sorcerer/cache_utils.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL dbg_jtag_avalon
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file config.vhd VHDL PATH sorcerer/config.vhd
add_fileset_file dbg_avalon_bridge.vhd VHDL PATH sorcerer/dbg_avalon_bridge.vhd
add_fileset_file dbg_crc.vhd VHDL PATH sorcerer/dbg_crc.vhd
add_fileset_file dbg_jtag_avalon.vhd VHDL PATH sorcerer/dbg_jtag_avalon.vhd
add_fileset_file dbg_jtag_transport.vhd VHDL PATH sorcerer/dbg_jtag_transport.vhd
add_fileset_file dbg_vjtag.vhd VHDL PATH sorcerer/dbg_vjtag.vhd
add_fileset_file iface.vhd VHDL PATH sorcerer/iface.vhd
add_fileset_file pipeline_iface.vhd VHDL PATH sorcerer/pipeline_iface.vhd
add_fileset_file utils.vhd VHDL PATH sorcerer/utils.vhd
add_fileset_file csr.vhd VHDL PATH sorcerer/csr.vhd
add_fileset_file cache_utils.vhd VHDL PATH sorcerer/cache_utils.vhd


# 
# parameters
# 
add_parameter SERIAL_WIDTH INTEGER 32
set_parameter_property SERIAL_WIDTH DEFAULT_VALUE 32
set_parameter_property SERIAL_WIDTH DISPLAY_NAME SERIAL_WIDTH
set_parameter_property SERIAL_WIDTH TYPE INTEGER
set_parameter_property SERIAL_WIDTH UNITS None
set_parameter_property SERIAL_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SERIAL_WIDTH HDL_PARAMETER true
add_parameter INT_BITS INTEGER 1
set_parameter_property INT_BITS DEFAULT_VALUE 1
set_parameter_property INT_BITS DISPLAY_NAME INT_BITS
set_parameter_property INT_BITS TYPE INTEGER
set_parameter_property INT_BITS UNITS None
set_parameter_property INT_BITS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property INT_BITS HDL_PARAMETER true
add_parameter SER_BITS INTEGER 1
set_parameter_property SER_BITS DEFAULT_VALUE 1
set_parameter_property SER_BITS DISPLAY_NAME SER_BITS
set_parameter_property SER_BITS TYPE INTEGER
set_parameter_property SER_BITS UNITS None
set_parameter_property SER_BITS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SER_BITS HDL_PARAMETER true
add_parameter VERSION INTEGER 1
set_parameter_property VERSION DEFAULT_VALUE 1
set_parameter_property VERSION DISPLAY_NAME VERSION
set_parameter_property VERSION TYPE INTEGER
set_parameter_property VERSION UNITS None
set_parameter_property VERSION ALLOWED_RANGES -2147483648:2147483647
set_parameter_property VERSION HDL_PARAMETER true
add_parameter PART_NUMBER INTEGER 1
set_parameter_property PART_NUMBER DEFAULT_VALUE 1
set_parameter_property PART_NUMBER DISPLAY_NAME PART_NUMBER
set_parameter_property PART_NUMBER TYPE INTEGER
set_parameter_property PART_NUMBER UNITS None
set_parameter_property PART_NUMBER ALLOWED_RANGES -2147483648:2147483647
set_parameter_property PART_NUMBER HDL_PARAMETER true
add_parameter MANUF_ID INTEGER 1
set_parameter_property MANUF_ID DEFAULT_VALUE 1
set_parameter_property MANUF_ID DISPLAY_NAME MANUF_ID
set_parameter_property MANUF_ID TYPE INTEGER
set_parameter_property MANUF_ID UNITS None
set_parameter_property MANUF_ID ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MANUF_ID HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point dbgm
# 
add_interface dbgm avalon start
set_interface_property dbgm addressUnits SYMBOLS
set_interface_property dbgm associatedClock clock
set_interface_property dbgm associatedReset sys_reset
set_interface_property dbgm bitsPerSymbol 8
set_interface_property dbgm burstOnBurstBoundariesOnly false
set_interface_property dbgm burstcountUnits WORDS
set_interface_property dbgm doStreamReads false
set_interface_property dbgm doStreamWrites false
set_interface_property dbgm holdTime 0
set_interface_property dbgm linewrapBursts false
set_interface_property dbgm maximumPendingReadTransactions 1
set_interface_property dbgm maximumPendingWriteTransactions 0
set_interface_property dbgm readLatency 0
set_interface_property dbgm readWaitTime 1
set_interface_property dbgm setupTime 0
set_interface_property dbgm timingUnits Cycles
set_interface_property dbgm writeWaitTime 0
set_interface_property dbgm ENABLED true
set_interface_property dbgm EXPORT_OF ""
set_interface_property dbgm PORT_NAME_MAP ""
set_interface_property dbgm CMSIS_SVD_VARIABLES ""
set_interface_property dbgm SVD_ADDRESS_GROUP ""

add_interface_port dbgm avm_dbgm_address address Output 32
add_interface_port dbgm avm_dbgm_read read Output 1
add_interface_port dbgm avm_dbgm_readdata readdata Input 32
add_interface_port dbgm avm_dbgm_readdatavalid readdatavalid Input 1
add_interface_port dbgm avm_dbgm_write write Output 1
add_interface_port dbgm avm_dbgm_writedata writedata Output 32
add_interface_port dbgm avm_dbgm_byteenable byteenable Output 4
add_interface_port dbgm avm_dbgm_waitrequest waitrequest Input 1


# 
# connection point reset_source
# 
add_interface reset_source reset start
set_interface_property reset_source associatedClock clock
set_interface_property reset_source associatedDirectReset ""
set_interface_property reset_source associatedResetSinks ""
set_interface_property reset_source synchronousEdges DEASSERT
set_interface_property reset_source ENABLED true
set_interface_property reset_source EXPORT_OF ""
set_interface_property reset_source PORT_NAME_MAP ""
set_interface_property reset_source CMSIS_SVD_VARIABLES ""
set_interface_property reset_source SVD_ADDRESS_GROUP ""

add_interface_port reset_source dbg_reset reset Output 1


# 
# connection point sys_reset
# 
add_interface sys_reset reset end
set_interface_property sys_reset associatedClock clock
set_interface_property sys_reset synchronousEdges DEASSERT
set_interface_property sys_reset ENABLED true
set_interface_property sys_reset EXPORT_OF ""
set_interface_property sys_reset PORT_NAME_MAP ""
set_interface_property sys_reset CMSIS_SVD_VARIABLES ""
set_interface_property sys_reset SVD_ADDRESS_GROUP ""

add_interface_port sys_reset sys_reset reset Input 1


# 
# connection point dbg_ndreset
# 
add_interface dbg_ndreset conduit end
set_interface_property dbg_ndreset associatedClock clock
set_interface_property dbg_ndreset associatedReset ""
set_interface_property dbg_ndreset ENABLED true
set_interface_property dbg_ndreset EXPORT_OF ""
set_interface_property dbg_ndreset PORT_NAME_MAP ""
set_interface_property dbg_ndreset CMSIS_SVD_VARIABLES ""
set_interface_property dbg_ndreset SVD_ADDRESS_GROUP ""

add_interface_port dbg_ndreset dbg_ndreset export Output 1

