# TCL File Generated by Component Editor 16.1
# Sat Sep 09 10:21:59 GMT+03:00 2017
# DO NOT MODIFY


# 
# led_monotor "LED Monotor" v1.0
#  2017.09.09.10:21:59
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module led_monotor
# 
set_module_property DESCRIPTION ""
set_module_property NAME led_monotor
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "LED Monotor"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL led_monitor
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file led_monitor.vhd VHDL PATH periph/led_monitor.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter REFRESH_PERIOD NATURAL 35000000
set_parameter_property REFRESH_PERIOD DEFAULT_VALUE 35000000
set_parameter_property REFRESH_PERIOD DISPLAY_NAME REFRESH_PERIOD
set_parameter_property REFRESH_PERIOD TYPE NATURAL
set_parameter_property REFRESH_PERIOD UNITS None
set_parameter_property REFRESH_PERIOD ALLOWED_RANGES 0:2147483647
set_parameter_property REFRESH_PERIOD HDL_PARAMETER true
add_parameter BLINK_PERIOD NATURAL 30000000
set_parameter_property BLINK_PERIOD DEFAULT_VALUE 30000000
set_parameter_property BLINK_PERIOD DISPLAY_NAME BLINK_PERIOD
set_parameter_property BLINK_PERIOD TYPE NATURAL
set_parameter_property BLINK_PERIOD UNITS None
set_parameter_property BLINK_PERIOD HDL_PARAMETER true
add_parameter READY_WAIT_TIMEOUT NATURAL 100
set_parameter_property READY_WAIT_TIMEOUT DEFAULT_VALUE 100
set_parameter_property READY_WAIT_TIMEOUT DISPLAY_NAME READY_WAIT_TIMEOUT
set_parameter_property READY_WAIT_TIMEOUT TYPE NATURAL
set_parameter_property READY_WAIT_TIMEOUT UNITS None
set_parameter_property READY_WAIT_TIMEOUT HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point hex0
# 
add_interface hex0 conduit end
set_interface_property hex0 associatedClock clock
set_interface_property hex0 associatedReset ""
set_interface_property hex0 ENABLED true
set_interface_property hex0 EXPORT_OF ""
set_interface_property hex0 PORT_NAME_MAP ""
set_interface_property hex0 CMSIS_SVD_VARIABLES ""
set_interface_property hex0 SVD_ADDRESS_GROUP ""

add_interface_port hex0 hex0 export Output 7


# 
# connection point hex1
# 
add_interface hex1 conduit end
set_interface_property hex1 associatedClock clock
set_interface_property hex1 associatedReset ""
set_interface_property hex1 ENABLED true
set_interface_property hex1 EXPORT_OF ""
set_interface_property hex1 PORT_NAME_MAP ""
set_interface_property hex1 CMSIS_SVD_VARIABLES ""
set_interface_property hex1 SVD_ADDRESS_GROUP ""

add_interface_port hex1 hex1 export Output 7


# 
# connection point hex2
# 
add_interface hex2 conduit end
set_interface_property hex2 associatedClock clock
set_interface_property hex2 associatedReset ""
set_interface_property hex2 ENABLED true
set_interface_property hex2 EXPORT_OF ""
set_interface_property hex2 PORT_NAME_MAP ""
set_interface_property hex2 CMSIS_SVD_VARIABLES ""
set_interface_property hex2 SVD_ADDRESS_GROUP ""

add_interface_port hex2 hex2 export Output 7


# 
# connection point hex3
# 
add_interface hex3 conduit end
set_interface_property hex3 associatedClock clock
set_interface_property hex3 associatedReset ""
set_interface_property hex3 ENABLED true
set_interface_property hex3 EXPORT_OF ""
set_interface_property hex3 PORT_NAME_MAP ""
set_interface_property hex3 CMSIS_SVD_VARIABLES ""
set_interface_property hex3 SVD_ADDRESS_GROUP ""

add_interface_port hex3 hex3 export Output 7


# 
# connection point hex4
# 
add_interface hex4 conduit end
set_interface_property hex4 associatedClock clock
set_interface_property hex4 associatedReset ""
set_interface_property hex4 ENABLED true
set_interface_property hex4 EXPORT_OF ""
set_interface_property hex4 PORT_NAME_MAP ""
set_interface_property hex4 CMSIS_SVD_VARIABLES ""
set_interface_property hex4 SVD_ADDRESS_GROUP ""

add_interface_port hex4 hex4 export Output 7


# 
# connection point hex5
# 
add_interface hex5 conduit end
set_interface_property hex5 associatedClock clock
set_interface_property hex5 associatedReset ""
set_interface_property hex5 ENABLED true
set_interface_property hex5 EXPORT_OF ""
set_interface_property hex5 PORT_NAME_MAP ""
set_interface_property hex5 CMSIS_SVD_VARIABLES ""
set_interface_property hex5 SVD_ADDRESS_GROUP ""

add_interface_port hex5 hex5 export Output 7


# 
# connection point data
# 
add_interface data conduit end
set_interface_property data associatedClock clock
set_interface_property data associatedReset ""
set_interface_property data ENABLED true
set_interface_property data EXPORT_OF ""
set_interface_property data PORT_NAME_MAP ""
set_interface_property data CMSIS_SVD_VARIABLES ""
set_interface_property data SVD_ADDRESS_GROUP ""

add_interface_port data data export Input 32


# 
# connection point valid
# 
add_interface valid conduit end
set_interface_property valid associatedClock clock
set_interface_property valid associatedReset ""
set_interface_property valid ENABLED true
set_interface_property valid EXPORT_OF ""
set_interface_property valid PORT_NAME_MAP ""
set_interface_property valid CMSIS_SVD_VARIABLES ""
set_interface_property valid SVD_ADDRESS_GROUP ""

add_interface_port valid valid export Input 1

