# TCL File Generated by Component Editor 16.1
# Thu Jul 20 21:14:15 GMT+03:00 2017
# DO NOT MODIFY


# 
# plic "plic" v1.0
#  2017.07.20.21:14:15
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module plic
# 
set_module_property DESCRIPTION ""
set_module_property NAME plic
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME plic
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL plic8
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file plic.vhd VHDL PATH sorcerer/plic.vhd
add_fileset_file utils.vhd VHDL PATH sorcerer/utils.vhd
add_fileset_file config.vhd VHDL PATH sorcerer/config.vhd
add_fileset_file plic8.vhd VHDL PATH sorcerer/plic8.vhd TOP_LEVEL_FILE
add_fileset_file iface.vhd VHDL PATH sorcerer/iface.vhd
add_fileset_file pipeline_iface.vhd VHDL PATH sorcerer/pipeline_iface.vhd
add_fileset_file csr.vhd VHDL PATH sorcerer/csr.vhd
add_fileset_file cache_utils.vhd VHDL PATH sorcerer/cache_utils.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL plic8
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file plic.vhd VHDL PATH sorcerer/plic.vhd
add_fileset_file utils.vhd VHDL PATH sorcerer/utils.vhd
add_fileset_file config.vhd VHDL PATH sorcerer/config.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point s1
# 
add_interface s1 avalon end
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock clock
set_interface_property s1 associatedReset reset
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 maximumPendingWriteTransactions 0
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true
set_interface_property s1 EXPORT_OF ""
set_interface_property s1 PORT_NAME_MAP ""
set_interface_property s1 CMSIS_SVD_VARIABLES ""
set_interface_property s1 SVD_ADDRESS_GROUP ""

add_interface_port s1 avs_s1_address address Input 3
add_interface_port s1 avs_s1_writedata writedata Input 32
add_interface_port s1 avs_s1_chipselect chipselect Input 1
add_interface_port s1 avs_s1_read read Input 1
add_interface_port s1 avs_s1_write write Input 1
add_interface_port s1 avs_s1_readdata readdata Output 32
set_interface_assignment s1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point intr
# 
add_interface intr conduit end
set_interface_property intr associatedClock clock
set_interface_property intr associatedReset ""
set_interface_property intr ENABLED true
set_interface_property intr EXPORT_OF ""
set_interface_property intr PORT_NAME_MAP ""
set_interface_property intr CMSIS_SVD_VARIABLES ""
set_interface_property intr SVD_ADDRESS_GROUP ""

add_interface_port intr intr irq Output 1


# 
# connection point irq0
# 
add_interface irq0 conduit end
set_interface_property irq0 associatedClock clock
set_interface_property irq0 associatedReset ""
set_interface_property irq0 ENABLED true
set_interface_property irq0 EXPORT_OF ""
set_interface_property irq0 PORT_NAME_MAP ""
set_interface_property irq0 CMSIS_SVD_VARIABLES ""
set_interface_property irq0 SVD_ADDRESS_GROUP ""

add_interface_port irq0 irq0 irq Input 1


# 
# connection point irq1
# 
add_interface irq1 conduit end
set_interface_property irq1 associatedClock clock
set_interface_property irq1 associatedReset ""
set_interface_property irq1 ENABLED true
set_interface_property irq1 EXPORT_OF ""
set_interface_property irq1 PORT_NAME_MAP ""
set_interface_property irq1 CMSIS_SVD_VARIABLES ""
set_interface_property irq1 SVD_ADDRESS_GROUP ""

add_interface_port irq1 irq1 irq Input 1


# 
# connection point irq2
# 
add_interface irq2 conduit end
set_interface_property irq2 associatedClock clock
set_interface_property irq2 associatedReset ""
set_interface_property irq2 ENABLED true
set_interface_property irq2 EXPORT_OF ""
set_interface_property irq2 PORT_NAME_MAP ""
set_interface_property irq2 CMSIS_SVD_VARIABLES ""
set_interface_property irq2 SVD_ADDRESS_GROUP ""

add_interface_port irq2 irq2 irq Input 1


# 
# connection point irq3
# 
add_interface irq3 conduit end
set_interface_property irq3 associatedClock clock
set_interface_property irq3 associatedReset ""
set_interface_property irq3 ENABLED true
set_interface_property irq3 EXPORT_OF ""
set_interface_property irq3 PORT_NAME_MAP ""
set_interface_property irq3 CMSIS_SVD_VARIABLES ""
set_interface_property irq3 SVD_ADDRESS_GROUP ""

add_interface_port irq3 irq3 irq Input 1


# 
# connection point irq4
# 
add_interface irq4 conduit end
set_interface_property irq4 associatedClock clock
set_interface_property irq4 associatedReset ""
set_interface_property irq4 ENABLED true
set_interface_property irq4 EXPORT_OF ""
set_interface_property irq4 PORT_NAME_MAP ""
set_interface_property irq4 CMSIS_SVD_VARIABLES ""
set_interface_property irq4 SVD_ADDRESS_GROUP ""

add_interface_port irq4 irq4 irq Input 1


# 
# connection point irq5
# 
add_interface irq5 conduit end
set_interface_property irq5 associatedClock clock
set_interface_property irq5 associatedReset ""
set_interface_property irq5 ENABLED true
set_interface_property irq5 EXPORT_OF ""
set_interface_property irq5 PORT_NAME_MAP ""
set_interface_property irq5 CMSIS_SVD_VARIABLES ""
set_interface_property irq5 SVD_ADDRESS_GROUP ""

add_interface_port irq5 irq5 irq Input 1


# 
# connection point irq6
# 
add_interface irq6 conduit end
set_interface_property irq6 associatedClock clock
set_interface_property irq6 associatedReset ""
set_interface_property irq6 ENABLED true
set_interface_property irq6 EXPORT_OF ""
set_interface_property irq6 PORT_NAME_MAP ""
set_interface_property irq6 CMSIS_SVD_VARIABLES ""
set_interface_property irq6 SVD_ADDRESS_GROUP ""

add_interface_port irq6 irq6 irq Input 1


# 
# connection point irq7
# 
add_interface irq7 conduit end
set_interface_property irq7 associatedClock clock
set_interface_property irq7 associatedReset ""
set_interface_property irq7 ENABLED true
set_interface_property irq7 EXPORT_OF ""
set_interface_property irq7 PORT_NAME_MAP ""
set_interface_property irq7 CMSIS_SVD_VARIABLES ""
set_interface_property irq7 SVD_ADDRESS_GROUP ""

add_interface_port irq7 irq7 irq Input 1

