# TCL File Generated by Component Editor 11.0
# Tue Jan 15 15:13:25 GMT+04:00 2013
# DO NOT MODIFY


# +-----------------------------------
# | 
# | pll2 "pll2" v1.0
# | null 2013.01.15.15:13:25
# | 
# | 
# | C:/qdesigns/BK_SOC4/src/pll2.vhd
# | 
# |    ./pll2.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module pll2
# | 
set_module_property NAME pll2
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME pll2
set_module_property TOP_LEVEL_HDL_FILE periph/pll2.vhd
set_module_property TOP_LEVEL_HDL_MODULE pll2
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME ""
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file pll2.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_sink
# | 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0

set_interface_property clock_sink ENABLED true

add_interface_port clock_sink inclk0 clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_source
# | 
add_interface clock_source clock start
set_interface_property clock_source associatedDirectClock ""
set_interface_property clock_source clockRate 50000000
set_interface_property clock_source clockRateKnown true

set_interface_property clock_source ENABLED true

add_interface_port clock_source c0 clk Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_source_1
# | 
add_interface clock_source_1 clock start
set_interface_property clock_source_1 associatedDirectClock ""
set_interface_property clock_source_1 clockRate 50000000
set_interface_property clock_source_1 clockRateKnown true

set_interface_property clock_source_1 ENABLED true

add_interface_port clock_source_1 c1 clk Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_source_2
# | 
add_interface clock_source_2 clock start
set_interface_property clock_source_2 associatedDirectClock ""
set_interface_property clock_source_2 clockRate 31500000
set_interface_property clock_source_2 clockRateKnown true

set_interface_property clock_source_2 ENABLED true

add_interface_port clock_source_2 c2 clk Output 1
# | 
# +-----------------------------------
