# TCL File Generated by Component Editor 16.1
# Fri Jun 02 04:01:52 GMT+03:00 2017
# DO NOT MODIFY


# 
# sdcard "sdcard" v1.0
#  2017.06.02.04:01:52
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module sdcard
# 
set_module_property DESCRIPTION ""
set_module_property NAME sdcard
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME sdcard
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL sdcard
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file bistable_domain_cross.v VERILOG PATH periph/sd/bistable_domain_cross.v
add_fileset_file edge_detect.v VERILOG PATH periph/sd/edge_detect.v
add_fileset_file generic_dpram.v VERILOG PATH periph/sd/generic_dpram.v
add_fileset_file generic_fifo_dc_gray.v VERILOG PATH periph/sd/generic_fifo_dc_gray.v
add_fileset_file monostable_domain_cross.v VERILOG PATH periph/sd/monostable_domain_cross.v
add_fileset_file sd_clock_divider.v VERILOG PATH periph/sd/sd_clock_divider.v
add_fileset_file sd_cmd_master.v VERILOG PATH periph/sd/sd_cmd_master.v
add_fileset_file sd_cmd_serial_host.v VERILOG PATH periph/sd/sd_cmd_serial_host.v
add_fileset_file sd_controller_wb.v VERILOG PATH periph/sd/sd_controller_wb.v
add_fileset_file sd_crc_16.v VERILOG PATH periph/sd/sd_crc_16.v
add_fileset_file sd_crc_7.v VERILOG PATH periph/sd/sd_crc_7.v
add_fileset_file sd_data_master.v VERILOG PATH periph/sd/sd_data_master.v
add_fileset_file sd_data_serial_host.v VERILOG PATH periph/sd/sd_data_serial_host.v
add_fileset_file sd_data_xfer_trig.v VERILOG PATH periph/sd/sd_data_xfer_trig.v
add_fileset_file sd_defines.h OTHER PATH periph/sd/sd_defines.h
add_fileset_file sd_fifo_filler.v VERILOG PATH periph/sd/sd_fifo_filler.v
add_fileset_file sdc_controller.v VERILOG PATH periph/sd/sdc_controller.v
add_fileset_file sdcard.vhd VHDL PATH periph/sd/sdcard.vhd TOP_LEVEL_FILE

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL sdcard
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file bistable_domain_cross.v VERILOG PATH periph/sd/bistable_domain_cross.v
add_fileset_file edge_detect.v VERILOG PATH periph/sd/edge_detect.v
add_fileset_file generic_dpram.v VERILOG PATH periph/sd/generic_dpram.v
add_fileset_file generic_fifo_dc_gray.v VERILOG PATH periph/sd/generic_fifo_dc_gray.v
add_fileset_file monostable_domain_cross.v VERILOG PATH periph/sd/monostable_domain_cross.v
add_fileset_file sd_clock_divider.v VERILOG PATH periph/sd/sd_clock_divider.v
add_fileset_file sd_cmd_master.v VERILOG PATH periph/sd/sd_cmd_master.v
add_fileset_file sd_cmd_serial_host.v VERILOG PATH periph/sd/sd_cmd_serial_host.v
add_fileset_file sd_controller_wb.v VERILOG PATH periph/sd/sd_controller_wb.v
add_fileset_file sd_crc_16.v VERILOG PATH periph/sd/sd_crc_16.v
add_fileset_file sd_crc_7.v VERILOG PATH periph/sd/sd_crc_7.v
add_fileset_file sd_data_master.v VERILOG PATH periph/sd/sd_data_master.v
add_fileset_file sd_data_serial_host.v VERILOG PATH periph/sd/sd_data_serial_host.v
add_fileset_file sd_data_xfer_trig.v VERILOG PATH periph/sd/sd_data_xfer_trig.v
add_fileset_file sd_defines.h OTHER PATH periph/sd/sd_defines.h
add_fileset_file sd_fifo_filler.v VERILOG PATH periph/sd/sd_fifo_filler.v
add_fileset_file sdc_controller.v VERILOG PATH periph/sd/sdc_controller.v
add_fileset_file sdcard.vhd VHDL PATH periph/sd/sdcard.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point s1
# 
add_interface s1 avalon end
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock clock
set_interface_property s1 associatedReset reset
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 maximumPendingWriteTransactions 0
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true
set_interface_property s1 EXPORT_OF ""
set_interface_property s1 PORT_NAME_MAP ""
set_interface_property s1 CMSIS_SVD_VARIABLES ""
set_interface_property s1 SVD_ADDRESS_GROUP ""

add_interface_port s1 avs_s1_address address Input 8
add_interface_port s1 avs_s1_writedata writedata Input 32
add_interface_port s1 avs_s1_chipselect chipselect Input 1
add_interface_port s1 avs_s1_read read Input 1
add_interface_port s1 avs_s1_write write Input 1
add_interface_port s1 avs_s1_byteenable byteenable Input 4
add_interface_port s1 avs_s1_readdata readdata Output 32
add_interface_port s1 avs_s1_waitrequest waitrequest Output 1
set_interface_assignment s1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point m1
# 
add_interface m1 avalon start
set_interface_property m1 addressUnits SYMBOLS
set_interface_property m1 associatedClock clock
set_interface_property m1 associatedReset reset
set_interface_property m1 bitsPerSymbol 8
set_interface_property m1 burstOnBurstBoundariesOnly false
set_interface_property m1 burstcountUnits WORDS
set_interface_property m1 doStreamReads false
set_interface_property m1 doStreamWrites false
set_interface_property m1 holdTime 0
set_interface_property m1 linewrapBursts false
set_interface_property m1 maximumPendingReadTransactions 0
set_interface_property m1 maximumPendingWriteTransactions 0
set_interface_property m1 readLatency 0
set_interface_property m1 readWaitTime 1
set_interface_property m1 setupTime 0
set_interface_property m1 timingUnits Cycles
set_interface_property m1 writeWaitTime 0
set_interface_property m1 ENABLED true
set_interface_property m1 EXPORT_OF ""
set_interface_property m1 PORT_NAME_MAP ""
set_interface_property m1 CMSIS_SVD_VARIABLES ""
set_interface_property m1 SVD_ADDRESS_GROUP ""

add_interface_port m1 avm_m1_address address Output 32
add_interface_port m1 avm_m1_writedata writedata Output 32
add_interface_port m1 avm_m1_read read Output 1
add_interface_port m1 avm_m1_write write Output 1
add_interface_port m1 avm_m1_byteenable byteenable Output 4
add_interface_port m1 avm_m1_readdata readdata Input 32
add_interface_port m1 avm_m1_waitrequest waitrequest Input 1
add_interface_port m1 avm_m1_burstcount burstcount Output 5
add_interface_port m1 avm_m1_readdatavalid readdatavalid Input 1


# 
# connection point sd
# 
add_interface sd conduit end
set_interface_property sd associatedClock clock
set_interface_property sd associatedReset ""
set_interface_property sd ENABLED true
set_interface_property sd EXPORT_OF ""
set_interface_property sd PORT_NAME_MAP ""
set_interface_property sd CMSIS_SVD_VARIABLES ""
set_interface_property sd SVD_ADDRESS_GROUP ""

add_interface_port sd sd_clk sd_clk Output 1
add_interface_port sd sd_cmd_in sd_cmd_in Input 1
add_interface_port sd sd_cmd_oe sd_cmd_oe Output 1
add_interface_port sd sd_cmd_out sd_cmd_out Output 1
add_interface_port sd sd_data_in sd_data_in Input 4
add_interface_port sd sd_data_oe sd_data_oe Output 1
add_interface_port sd sd_data_out sd_data_out Output 4


# 
# connection point int_cmd
# 
add_interface int_cmd conduit end
set_interface_property int_cmd associatedClock clock
set_interface_property int_cmd associatedReset ""
set_interface_property int_cmd ENABLED true
set_interface_property int_cmd EXPORT_OF ""
set_interface_property int_cmd PORT_NAME_MAP ""
set_interface_property int_cmd CMSIS_SVD_VARIABLES ""
set_interface_property int_cmd SVD_ADDRESS_GROUP ""

add_interface_port int_cmd int_cmd irq Output 1


# 
# connection point int_data
# 
add_interface int_data conduit end
set_interface_property int_data associatedClock clock
set_interface_property int_data associatedReset ""
set_interface_property int_data ENABLED true
set_interface_property int_data EXPORT_OF ""
set_interface_property int_data PORT_NAME_MAP ""
set_interface_property int_data CMSIS_SVD_VARIABLES ""
set_interface_property int_data SVD_ADDRESS_GROUP ""

add_interface_port int_data int_data irq Output 1

