# TCL File Generated by Component Editor 16.1
# Tue Sep 26 03:05:56 GMT+03:00 2017
# DO NOT MODIFY


# 
# sorcerer_cpu "Sorcerer" v1.0
#  2017.09.26.03:05:56
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module sorcerer_cpu
# 
set_module_property DESCRIPTION ""
set_module_property NAME sorcerer_cpu
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Sorcerer
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL sorcerer
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file alu.vhd VHDL PATH sorcerer/alu.vhd
add_fileset_file avalon_master.vhd VHDL PATH sorcerer/avalon_master.vhd
add_fileset_file cache_utils.vhd VHDL PATH sorcerer/cache_utils.vhd
add_fileset_file config.vhd VHDL PATH sorcerer/config.vhd
add_fileset_file csr.vhd VHDL PATH sorcerer/csr.vhd
add_fileset_file dbg_avalon_bridge.vhd VHDL PATH sorcerer/dbg_avalon_bridge.vhd
add_fileset_file dbg_crc.vhd VHDL PATH sorcerer/dbg_crc.vhd
add_fileset_file dbg_defs.vhd VHDL PATH sorcerer/dbg_defs.vhd
add_fileset_file dbg_jtag_avalon.vhd VHDL PATH sorcerer/dbg_jtag_avalon.vhd
add_fileset_file dbg_jtag_transport.vhd VHDL PATH sorcerer/dbg_jtag_transport.vhd
add_fileset_file dbg_module_avalon.vhd VHDL PATH sorcerer/dbg_module_avalon.vhd
add_fileset_file dbg_vjtag.vhd VHDL PATH sorcerer/dbg_vjtag.vhd
add_fileset_file dcache.vhd VHDL PATH sorcerer/dcache.vhd
add_fileset_file decoder_rv32c.vhd VHDL PATH sorcerer/decoder_rv32c.vhd
add_fileset_file decoder_rv32im.vhd VHDL PATH sorcerer/decoder_rv32im.vhd
add_fileset_file disassembler_rv32c.vhd VHDL PATH sorcerer/disassembler_rv32c.vhd
add_fileset_file disassembler_rv32im.vhd VHDL PATH sorcerer/disassembler_rv32im.vhd
add_fileset_file disassembler_utils.vhd VHDL PATH sorcerer/disassembler_utils.vhd
add_fileset_file div32x32.vhd VHDL PATH sorcerer/div32x32.vhd
add_fileset_file fifo_sc.vhd VHDL PATH sorcerer/fifo_sc.vhd
add_fileset_file gpr.vhd VHDL PATH sorcerer/gpr.vhd
add_fileset_file hw_breakpoints.vhd VHDL PATH sorcerer/hw_breakpoints.vhd
add_fileset_file icache.vhd VHDL PATH sorcerer/icache.vhd
add_fileset_file iface.vhd VHDL PATH sorcerer/iface.vhd
add_fileset_file lru.vhd VHDL PATH sorcerer/lru.vhd
add_fileset_file memory_map.vhd VHDL PATH sorcerer/memory_map.vhd
add_fileset_file mmu.vhd VHDL PATH sorcerer/mmu.vhd
add_fileset_file mmu_joint_tlb.vhd VHDL PATH sorcerer/mmu_joint_tlb.vhd
add_fileset_file mmu_tlb_cache.vhd VHDL PATH sorcerer/mmu_tlb_cache.vhd
add_fileset_file mul16x16.vhd VHDL PATH sorcerer/mul16x16.vhd
add_fileset_file mul32x32.vhd VHDL PATH sorcerer/mul32x32.vhd
add_fileset_file pipeline_iface.vhd VHDL PATH sorcerer/pipeline_iface.vhd
add_fileset_file pseudo_lru.vhd VHDL PATH sorcerer/pseudo_lru.vhd
add_fileset_file ram_avalon.vhd VHDL PATH sorcerer/ram_avalon.vhd
add_fileset_file ram_block.vhd VHDL PATH sorcerer/ram_block.vhd
add_fileset_file rv32c_utils.vhd VHDL PATH sorcerer/rv32c_utils.vhd
add_fileset_file sorcerer.vhd VHDL PATH sorcerer/sorcerer.vhd TOP_LEVEL_FILE
add_fileset_file trace.vhd VHDL PATH sorcerer/trace.vhd
add_fileset_file trace_fifo.vhd VHDL PATH sorcerer/trace_fifo.vhd
add_fileset_file utils.vhd VHDL PATH sorcerer/utils.vhd
add_fileset_file decompressor_rv32c.vhd VHDL PATH sorcerer/decompressor_rv32c.vhd
add_fileset_file ibuffer.vhd VHDL PATH sorcerer/ibuffer.vhd
add_fileset_file ibuffer_core.vhd VHDL PATH sorcerer/ibuffer_core.vhd
add_fileset_file barrel_shifter.vhd VHDL PATH sorcerer/barrel_shifter.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL sorcerer
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file alu.vhd VHDL PATH sorcerer/alu.vhd
add_fileset_file avalon_master.vhd VHDL PATH sorcerer/avalon_master.vhd
add_fileset_file cache_utils.vhd VHDL PATH sorcerer/cache_utils.vhd
add_fileset_file config.vhd VHDL PATH sorcerer/config.vhd
add_fileset_file csr.vhd VHDL PATH sorcerer/csr.vhd
add_fileset_file dbg_avalon_bridge.vhd VHDL PATH sorcerer/dbg_avalon_bridge.vhd
add_fileset_file dbg_crc.vhd VHDL PATH sorcerer/dbg_crc.vhd
add_fileset_file dbg_defs.vhd VHDL PATH sorcerer/dbg_defs.vhd
add_fileset_file dbg_jtag_avalon.vhd VHDL PATH sorcerer/dbg_jtag_avalon.vhd
add_fileset_file dbg_jtag_transport.vhd VHDL PATH sorcerer/dbg_jtag_transport.vhd
add_fileset_file dbg_module_avalon.vhd VHDL PATH sorcerer/dbg_module_avalon.vhd
add_fileset_file dbg_vjtag.vhd VHDL PATH sorcerer/dbg_vjtag.vhd
add_fileset_file dcache.vhd VHDL PATH sorcerer/dcache.vhd
add_fileset_file decoder_rv32c.vhd VHDL PATH sorcerer/decoder_rv32c.vhd
add_fileset_file decoder_rv32im.vhd VHDL PATH sorcerer/decoder_rv32im.vhd
add_fileset_file disassembler_rv32c.vhd VHDL PATH sorcerer/disassembler_rv32c.vhd
add_fileset_file disassembler_rv32im.vhd VHDL PATH sorcerer/disassembler_rv32im.vhd
add_fileset_file disassembler_utils.vhd VHDL PATH sorcerer/disassembler_utils.vhd
add_fileset_file div32x32.vhd VHDL PATH sorcerer/div32x32.vhd
add_fileset_file fifo_sc.vhd VHDL PATH sorcerer/fifo_sc.vhd
add_fileset_file gpr.vhd VHDL PATH sorcerer/gpr.vhd
add_fileset_file hw_breakpoints.vhd VHDL PATH sorcerer/hw_breakpoints.vhd
add_fileset_file icache.vhd VHDL PATH sorcerer/icache.vhd
add_fileset_file iface.vhd VHDL PATH sorcerer/iface.vhd
add_fileset_file lru.vhd VHDL PATH sorcerer/lru.vhd
add_fileset_file memory_map.vhd VHDL PATH sorcerer/memory_map.vhd
add_fileset_file mmu.vhd VHDL PATH sorcerer/mmu.vhd
add_fileset_file mmu_joint_tlb.vhd VHDL PATH sorcerer/mmu_joint_tlb.vhd
add_fileset_file mmu_tlb_cache.vhd VHDL PATH sorcerer/mmu_tlb_cache.vhd
add_fileset_file mul32x32.vhd VHDL PATH sorcerer/mul32x32.vhd
add_fileset_file pipeline_iface.vhd VHDL PATH sorcerer/pipeline_iface.vhd
add_fileset_file pseudo_lru.vhd VHDL PATH sorcerer/pseudo_lru.vhd
add_fileset_file ram_avalon.vhd VHDL PATH sorcerer/ram_avalon.vhd
add_fileset_file ram_block.vhd VHDL PATH sorcerer/ram_block.vhd
add_fileset_file rv32c_utils.vhd VHDL PATH sorcerer/rv32c_utils.vhd
add_fileset_file sorcerer.vhd VHDL PATH sorcerer/sorcerer.vhd
add_fileset_file trace.vhd VHDL PATH sorcerer/trace.vhd
add_fileset_file trace_fifo.vhd VHDL PATH sorcerer/trace_fifo.vhd
add_fileset_file utils.vhd VHDL PATH sorcerer/utils.vhd
add_fileset_file mul16x16.vhd VHDL PATH sorcerer/mul16x16.vhd
add_fileset_file decompressor_rv32c.vhd VHDL PATH sorcerer/decompressor_rv32c.vhd
add_fileset_file ibuffer.vhd VHDL PATH sorcerer/ibuffer.vhd
add_fileset_file ibuffer_core.vhd VHDL PATH sorcerer/ibuffer_core.vhd
add_fileset_file barrel_shifter.vhd VHDL PATH sorcerer/barrel_shifter.vhd


# 
# parameters
# 
add_parameter ENABLE_A INTEGER 0
set_parameter_property ENABLE_A DEFAULT_VALUE 0
set_parameter_property ENABLE_A DISPLAY_NAME ENABLE_A
set_parameter_property ENABLE_A TYPE INTEGER
set_parameter_property ENABLE_A UNITS None
set_parameter_property ENABLE_A ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ENABLE_A HDL_PARAMETER true
add_parameter ENABLE_C INTEGER 0
set_parameter_property ENABLE_C DEFAULT_VALUE 0
set_parameter_property ENABLE_C DISPLAY_NAME ENABLE_C
set_parameter_property ENABLE_C TYPE INTEGER
set_parameter_property ENABLE_C UNITS None
set_parameter_property ENABLE_C ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ENABLE_C HDL_PARAMETER true
add_parameter ENABLE_D INTEGER 0
set_parameter_property ENABLE_D DEFAULT_VALUE 0
set_parameter_property ENABLE_D DISPLAY_NAME ENABLE_D
set_parameter_property ENABLE_D TYPE INTEGER
set_parameter_property ENABLE_D UNITS None
set_parameter_property ENABLE_D ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ENABLE_D HDL_PARAMETER true
add_parameter ENABLE_E INTEGER 0
set_parameter_property ENABLE_E DEFAULT_VALUE 0
set_parameter_property ENABLE_E DISPLAY_NAME ENABLE_E
set_parameter_property ENABLE_E TYPE INTEGER
set_parameter_property ENABLE_E UNITS None
set_parameter_property ENABLE_E ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ENABLE_E HDL_PARAMETER true
add_parameter ENABLE_F INTEGER 0
set_parameter_property ENABLE_F DEFAULT_VALUE 0
set_parameter_property ENABLE_F DISPLAY_NAME ENABLE_F
set_parameter_property ENABLE_F TYPE INTEGER
set_parameter_property ENABLE_F UNITS None
set_parameter_property ENABLE_F ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ENABLE_F HDL_PARAMETER true
add_parameter ENABLE_G INTEGER 0
set_parameter_property ENABLE_G DEFAULT_VALUE 0
set_parameter_property ENABLE_G DISPLAY_NAME ENABLE_G
set_parameter_property ENABLE_G TYPE INTEGER
set_parameter_property ENABLE_G UNITS None
set_parameter_property ENABLE_G ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ENABLE_G HDL_PARAMETER true
add_parameter ENABLE_M INTEGER 1
set_parameter_property ENABLE_M DEFAULT_VALUE 1
set_parameter_property ENABLE_M DISPLAY_NAME ENABLE_M
set_parameter_property ENABLE_M TYPE INTEGER
set_parameter_property ENABLE_M UNITS None
set_parameter_property ENABLE_M ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ENABLE_M HDL_PARAMETER true
add_parameter ENABLE_N INTEGER 0
set_parameter_property ENABLE_N DEFAULT_VALUE 0
set_parameter_property ENABLE_N DISPLAY_NAME ENABLE_N
set_parameter_property ENABLE_N TYPE INTEGER
set_parameter_property ENABLE_N UNITS None
set_parameter_property ENABLE_N ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ENABLE_N HDL_PARAMETER true
add_parameter ENABLE_S INTEGER 0
set_parameter_property ENABLE_S DEFAULT_VALUE 0
set_parameter_property ENABLE_S DISPLAY_NAME ENABLE_S
set_parameter_property ENABLE_S TYPE INTEGER
set_parameter_property ENABLE_S UNITS None
set_parameter_property ENABLE_S ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ENABLE_S HDL_PARAMETER true
add_parameter ENABLE_U INTEGER 0
set_parameter_property ENABLE_U DEFAULT_VALUE 0
set_parameter_property ENABLE_U DISPLAY_NAME ENABLE_U
set_parameter_property ENABLE_U TYPE INTEGER
set_parameter_property ENABLE_U UNITS None
set_parameter_property ENABLE_U ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ENABLE_U HDL_PARAMETER true
add_parameter ENABLE_X INTEGER 0
set_parameter_property ENABLE_X DEFAULT_VALUE 0
set_parameter_property ENABLE_X DISPLAY_NAME ENABLE_X
set_parameter_property ENABLE_X TYPE INTEGER
set_parameter_property ENABLE_X UNITS None
set_parameter_property ENABLE_X ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ENABLE_X HDL_PARAMETER true
add_parameter ENABLE_SHIFTER INTEGER 0
set_parameter_property ENABLE_SHIFTER DEFAULT_VALUE 0
set_parameter_property ENABLE_SHIFTER DISPLAY_NAME ENABLE_SHIFTER
set_parameter_property ENABLE_SHIFTER TYPE INTEGER
set_parameter_property ENABLE_SHIFTER UNITS None
set_parameter_property ENABLE_SHIFTER ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ENABLE_SHIFTER HDL_PARAMETER true
add_parameter ENABLE_MMU INTEGER 0
set_parameter_property ENABLE_MMU DEFAULT_VALUE 0
set_parameter_property ENABLE_MMU DISPLAY_NAME ENABLE_MMU
set_parameter_property ENABLE_MMU TYPE INTEGER
set_parameter_property ENABLE_MMU UNITS None
set_parameter_property ENABLE_MMU ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ENABLE_MMU HDL_PARAMETER true
add_parameter ENABLE_CACHE INTEGER 1
set_parameter_property ENABLE_CACHE DEFAULT_VALUE 1
set_parameter_property ENABLE_CACHE DISPLAY_NAME ENABLE_CACHE
set_parameter_property ENABLE_CACHE TYPE INTEGER
set_parameter_property ENABLE_CACHE UNITS None
set_parameter_property ENABLE_CACHE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ENABLE_CACHE HDL_PARAMETER true
add_parameter ENABLE_DEBUG INTEGER 1
set_parameter_property ENABLE_DEBUG DEFAULT_VALUE 1
set_parameter_property ENABLE_DEBUG DISPLAY_NAME ENABLE_DEBUG
set_parameter_property ENABLE_DEBUG TYPE INTEGER
set_parameter_property ENABLE_DEBUG UNITS None
set_parameter_property ENABLE_DEBUG ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ENABLE_DEBUG HDL_PARAMETER true
add_parameter ENABLE_HW_BREAKPOINT INTEGER 0
set_parameter_property ENABLE_HW_BREAKPOINT DEFAULT_VALUE 0
set_parameter_property ENABLE_HW_BREAKPOINT DISPLAY_NAME ENABLE_HW_BREAKPOINT
set_parameter_property ENABLE_HW_BREAKPOINT TYPE INTEGER
set_parameter_property ENABLE_HW_BREAKPOINT UNITS None
set_parameter_property ENABLE_HW_BREAKPOINT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ENABLE_HW_BREAKPOINT HDL_PARAMETER true
add_parameter ENABLE_DEBUG_ROM1 INTEGER 1
set_parameter_property ENABLE_DEBUG_ROM1 DEFAULT_VALUE 1
set_parameter_property ENABLE_DEBUG_ROM1 DISPLAY_NAME ENABLE_DEBUG_ROM1
set_parameter_property ENABLE_DEBUG_ROM1 TYPE INTEGER
set_parameter_property ENABLE_DEBUG_ROM1 UNITS None
set_parameter_property ENABLE_DEBUG_ROM1 ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ENABLE_DEBUG_ROM1 HDL_PARAMETER true
add_parameter ENABLE_DEBUG_ROM2 INTEGER 0
set_parameter_property ENABLE_DEBUG_ROM2 DEFAULT_VALUE 0
set_parameter_property ENABLE_DEBUG_ROM2 DISPLAY_NAME ENABLE_DEBUG_ROM2
set_parameter_property ENABLE_DEBUG_ROM2 TYPE INTEGER
set_parameter_property ENABLE_DEBUG_ROM2 UNITS None
set_parameter_property ENABLE_DEBUG_ROM2 ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ENABLE_DEBUG_ROM2 HDL_PARAMETER true
add_parameter ENABLE_TRACE INTEGER 0
set_parameter_property ENABLE_TRACE DEFAULT_VALUE 0
set_parameter_property ENABLE_TRACE DISPLAY_NAME ENABLE_TRACE
set_parameter_property ENABLE_TRACE TYPE INTEGER
set_parameter_property ENABLE_TRACE UNITS None
set_parameter_property ENABLE_TRACE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ENABLE_TRACE HDL_PARAMETER true
add_parameter ENABLE_MISA INTEGER 0
set_parameter_property ENABLE_MISA DEFAULT_VALUE 0
set_parameter_property ENABLE_MISA DISPLAY_NAME ENABLE_MISA
set_parameter_property ENABLE_MISA TYPE INTEGER
set_parameter_property ENABLE_MISA UNITS None
set_parameter_property ENABLE_MISA ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ENABLE_MISA HDL_PARAMETER true
add_parameter ENABLE_MCYCLE INTEGER 0
set_parameter_property ENABLE_MCYCLE DEFAULT_VALUE 0
set_parameter_property ENABLE_MCYCLE DISPLAY_NAME ENABLE_MCYCLE
set_parameter_property ENABLE_MCYCLE TYPE INTEGER
set_parameter_property ENABLE_MCYCLE UNITS None
set_parameter_property ENABLE_MCYCLE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ENABLE_MCYCLE HDL_PARAMETER true
add_parameter ENABLE_MINSTRET INTEGER 0
set_parameter_property ENABLE_MINSTRET DEFAULT_VALUE 0
set_parameter_property ENABLE_MINSTRET DISPLAY_NAME ENABLE_MINSTRET
set_parameter_property ENABLE_MINSTRET TYPE INTEGER
set_parameter_property ENABLE_MINSTRET UNITS None
set_parameter_property ENABLE_MINSTRET ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ENABLE_MINSTRET HDL_PARAMETER true
add_parameter ENABLE_BADADDR INTEGER 1
set_parameter_property ENABLE_BADADDR DEFAULT_VALUE 1
set_parameter_property ENABLE_BADADDR DISPLAY_NAME ENABLE_BADADDR
set_parameter_property ENABLE_BADADDR TYPE INTEGER
set_parameter_property ENABLE_BADADDR UNITS None
set_parameter_property ENABLE_BADADDR ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ENABLE_BADADDR HDL_PARAMETER true
add_parameter ITLB_CACHE_SIZE INTEGER 4
set_parameter_property ITLB_CACHE_SIZE DEFAULT_VALUE 4
set_parameter_property ITLB_CACHE_SIZE DISPLAY_NAME ITLB_CACHE_SIZE
set_parameter_property ITLB_CACHE_SIZE TYPE INTEGER
set_parameter_property ITLB_CACHE_SIZE UNITS None
set_parameter_property ITLB_CACHE_SIZE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ITLB_CACHE_SIZE HDL_PARAMETER true
add_parameter DTLB_CACHE_SIZE INTEGER 4
set_parameter_property DTLB_CACHE_SIZE DEFAULT_VALUE 4
set_parameter_property DTLB_CACHE_SIZE DISPLAY_NAME DTLB_CACHE_SIZE
set_parameter_property DTLB_CACHE_SIZE TYPE INTEGER
set_parameter_property DTLB_CACHE_SIZE UNITS None
set_parameter_property DTLB_CACHE_SIZE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DTLB_CACHE_SIZE HDL_PARAMETER true
add_parameter JOINT_TLB_SIZE INTEGER 32
set_parameter_property JOINT_TLB_SIZE DEFAULT_VALUE 32
set_parameter_property JOINT_TLB_SIZE DISPLAY_NAME JOINT_TLB_SIZE
set_parameter_property JOINT_TLB_SIZE TYPE INTEGER
set_parameter_property JOINT_TLB_SIZE UNITS None
set_parameter_property JOINT_TLB_SIZE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property JOINT_TLB_SIZE HDL_PARAMETER true
add_parameter RAM_SIZE INTEGER 16384
set_parameter_property RAM_SIZE DEFAULT_VALUE 16384
set_parameter_property RAM_SIZE DISPLAY_NAME RAM_SIZE
set_parameter_property RAM_SIZE TYPE INTEGER
set_parameter_property RAM_SIZE UNITS None
set_parameter_property RAM_SIZE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property RAM_SIZE HDL_PARAMETER true
add_parameter RAM_START_ADDRESS STD_LOGIC_VECTOR 2147483648
set_parameter_property RAM_START_ADDRESS DEFAULT_VALUE 2147483648
set_parameter_property RAM_START_ADDRESS DISPLAY_NAME RAM_START_ADDRESS
set_parameter_property RAM_START_ADDRESS TYPE STD_LOGIC_VECTOR
set_parameter_property RAM_START_ADDRESS UNITS None
set_parameter_property RAM_START_ADDRESS ALLOWED_RANGES 0:4294967295
set_parameter_property RAM_START_ADDRESS HDL_PARAMETER true
add_parameter RAM_INIT_FILE STRING ""
set_parameter_property RAM_INIT_FILE DEFAULT_VALUE ""
set_parameter_property RAM_INIT_FILE DISPLAY_NAME RAM_INIT_FILE
set_parameter_property RAM_INIT_FILE TYPE STRING
set_parameter_property RAM_INIT_FILE UNITS None
set_parameter_property RAM_INIT_FILE HDL_PARAMETER true
add_parameter INSN_BP_NUM INTEGER 4
set_parameter_property INSN_BP_NUM DEFAULT_VALUE 4
set_parameter_property INSN_BP_NUM DISPLAY_NAME INSN_BP_NUM
set_parameter_property INSN_BP_NUM TYPE INTEGER
set_parameter_property INSN_BP_NUM UNITS None
set_parameter_property INSN_BP_NUM ALLOWED_RANGES -2147483648:2147483647
set_parameter_property INSN_BP_NUM HDL_PARAMETER true
add_parameter DATA_BP_NUM INTEGER 2
set_parameter_property DATA_BP_NUM DEFAULT_VALUE 2
set_parameter_property DATA_BP_NUM DISPLAY_NAME DATA_BP_NUM
set_parameter_property DATA_BP_NUM TYPE INTEGER
set_parameter_property DATA_BP_NUM UNITS None
set_parameter_property DATA_BP_NUM ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_BP_NUM HDL_PARAMETER true
add_parameter TRACE_FIFO_SIZE INTEGER 2048
set_parameter_property TRACE_FIFO_SIZE DEFAULT_VALUE 2048
set_parameter_property TRACE_FIFO_SIZE DISPLAY_NAME TRACE_FIFO_SIZE
set_parameter_property TRACE_FIFO_SIZE TYPE INTEGER
set_parameter_property TRACE_FIFO_SIZE UNITS None
set_parameter_property TRACE_FIFO_SIZE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property TRACE_FIFO_SIZE HDL_PARAMETER true
add_parameter TRACE_FIFO_WIDTH INTEGER 128
set_parameter_property TRACE_FIFO_WIDTH DEFAULT_VALUE 128
set_parameter_property TRACE_FIFO_WIDTH DISPLAY_NAME TRACE_FIFO_WIDTH
set_parameter_property TRACE_FIFO_WIDTH TYPE INTEGER
set_parameter_property TRACE_FIFO_WIDTH UNITS None
set_parameter_property TRACE_FIFO_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property TRACE_FIFO_WIDTH HDL_PARAMETER true
add_parameter TRACE_INIT_BUF_START INTEGER 0
set_parameter_property TRACE_INIT_BUF_START DEFAULT_VALUE 0
set_parameter_property TRACE_INIT_BUF_START DISPLAY_NAME TRACE_INIT_BUF_START
set_parameter_property TRACE_INIT_BUF_START TYPE INTEGER
set_parameter_property TRACE_INIT_BUF_START UNITS None
set_parameter_property TRACE_INIT_BUF_START ALLOWED_RANGES -2147483648:2147483647
set_parameter_property TRACE_INIT_BUF_START HDL_PARAMETER true
add_parameter TRACE_INIT_BUF_END INTEGER 0
set_parameter_property TRACE_INIT_BUF_END DEFAULT_VALUE 0
set_parameter_property TRACE_INIT_BUF_END DISPLAY_NAME TRACE_INIT_BUF_END
set_parameter_property TRACE_INIT_BUF_END TYPE INTEGER
set_parameter_property TRACE_INIT_BUF_END UNITS None
set_parameter_property TRACE_INIT_BUF_END ALLOWED_RANGES -2147483648:2147483647
set_parameter_property TRACE_INIT_BUF_END HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point mem
# 
add_interface mem avalon start
set_interface_property mem addressUnits SYMBOLS
set_interface_property mem associatedClock clock
set_interface_property mem associatedReset reset
set_interface_property mem bitsPerSymbol 8
set_interface_property mem burstOnBurstBoundariesOnly true
set_interface_property mem burstcountUnits WORDS
set_interface_property mem doStreamReads false
set_interface_property mem doStreamWrites false
set_interface_property mem holdTime 0
set_interface_property mem linewrapBursts false
set_interface_property mem maximumPendingReadTransactions 1
set_interface_property mem maximumPendingWriteTransactions 0
set_interface_property mem readLatency 0
set_interface_property mem readWaitTime 1
set_interface_property mem setupTime 0
set_interface_property mem timingUnits Cycles
set_interface_property mem writeWaitTime 0
set_interface_property mem ENABLED true
set_interface_property mem EXPORT_OF ""
set_interface_property mem PORT_NAME_MAP ""
set_interface_property mem CMSIS_SVD_VARIABLES ""
set_interface_property mem SVD_ADDRESS_GROUP ""

add_interface_port mem avm_mem_address address Output 32
add_interface_port mem avm_mem_burstcount burstcount Output 5
add_interface_port mem avm_mem_read read Output 1
add_interface_port mem avm_mem_readdata readdata Input 32
add_interface_port mem avm_mem_readdatavalid readdatavalid Input 1
add_interface_port mem avm_mem_write write Output 1
add_interface_port mem avm_mem_writedata writedata Output 32
add_interface_port mem avm_mem_byteenable byteenable Output 4
add_interface_port mem avm_mem_waitrequest waitrequest Input 1


# 
# connection point trace
# 
add_interface trace avalon start
set_interface_property trace addressUnits SYMBOLS
set_interface_property trace associatedClock clock
set_interface_property trace associatedReset reset
set_interface_property trace bitsPerSymbol 8
set_interface_property trace burstOnBurstBoundariesOnly false
set_interface_property trace burstcountUnits WORDS
set_interface_property trace doStreamReads false
set_interface_property trace doStreamWrites false
set_interface_property trace holdTime 0
set_interface_property trace linewrapBursts false
set_interface_property trace maximumPendingReadTransactions 0
set_interface_property trace maximumPendingWriteTransactions 0
set_interface_property trace readLatency 0
set_interface_property trace readWaitTime 1
set_interface_property trace setupTime 0
set_interface_property trace timingUnits Cycles
set_interface_property trace writeWaitTime 0
set_interface_property trace ENABLED true
set_interface_property trace EXPORT_OF ""
set_interface_property trace PORT_NAME_MAP ""
set_interface_property trace CMSIS_SVD_VARIABLES ""
set_interface_property trace SVD_ADDRESS_GROUP ""

add_interface_port trace avm_trace_address address Output 32
add_interface_port trace avm_trace_write write Output 1
add_interface_port trace avm_trace_writedata writedata Output 32
add_interface_port trace avm_trace_burstcount burstcount Output 4
add_interface_port trace avm_trace_byteenable byteenable Output 4
add_interface_port trace avm_trace_waitrequest waitrequest Input 1


# 
# connection point dbgm
# 
add_interface dbgm avalon end
set_interface_property dbgm addressUnits WORDS
set_interface_property dbgm associatedClock clock
set_interface_property dbgm associatedReset reset
set_interface_property dbgm bitsPerSymbol 8
set_interface_property dbgm burstOnBurstBoundariesOnly false
set_interface_property dbgm burstcountUnits WORDS
set_interface_property dbgm explicitAddressSpan 0
set_interface_property dbgm holdTime 0
set_interface_property dbgm linewrapBursts false
set_interface_property dbgm maximumPendingReadTransactions 1
set_interface_property dbgm maximumPendingWriteTransactions 0
set_interface_property dbgm readLatency 0
set_interface_property dbgm readWaitTime 1
set_interface_property dbgm setupTime 0
set_interface_property dbgm timingUnits Cycles
set_interface_property dbgm writeWaitTime 0
set_interface_property dbgm ENABLED true
set_interface_property dbgm EXPORT_OF ""
set_interface_property dbgm PORT_NAME_MAP ""
set_interface_property dbgm CMSIS_SVD_VARIABLES ""
set_interface_property dbgm SVD_ADDRESS_GROUP ""

add_interface_port dbgm avs_dbgm_address address Input 15
add_interface_port dbgm avs_dbgm_chipselect chipselect Input 1
add_interface_port dbgm avs_dbgm_write write Input 1
add_interface_port dbgm avs_dbgm_writedata writedata Input 32
add_interface_port dbgm avs_dbgm_read read Input 1
add_interface_port dbgm avs_dbgm_readdata readdata Output 32
add_interface_port dbgm avs_dbgm_readdatavalid readdatavalid Output 1
add_interface_port dbgm avs_dbgm_waitrequest waitrequest Output 1
set_interface_assignment dbgm embeddedsw.configuration.isFlash 0
set_interface_assignment dbgm embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment dbgm embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment dbgm embeddedsw.configuration.isPrintableDevice 0


# 
# connection point dbg_irq
# 
add_interface dbg_irq conduit end
set_interface_property dbg_irq associatedClock clock
set_interface_property dbg_irq associatedReset ""
set_interface_property dbg_irq ENABLED true
set_interface_property dbg_irq EXPORT_OF ""
set_interface_property dbg_irq PORT_NAME_MAP ""
set_interface_property dbg_irq CMSIS_SVD_VARIABLES ""
set_interface_property dbg_irq SVD_ADDRESS_GROUP ""

add_interface_port dbg_irq dbg_irq irq Input 1


# 
# connection point meip
# 
add_interface meip conduit end
set_interface_property meip associatedClock clock
set_interface_property meip associatedReset ""
set_interface_property meip ENABLED true
set_interface_property meip EXPORT_OF ""
set_interface_property meip PORT_NAME_MAP ""
set_interface_property meip CMSIS_SVD_VARIABLES ""
set_interface_property meip SVD_ADDRESS_GROUP ""

add_interface_port meip meip irq Input 1


# 
# connection point msip
# 
add_interface msip conduit end
set_interface_property msip associatedClock clock
set_interface_property msip associatedReset ""
set_interface_property msip ENABLED true
set_interface_property msip EXPORT_OF ""
set_interface_property msip PORT_NAME_MAP ""
set_interface_property msip CMSIS_SVD_VARIABLES ""
set_interface_property msip SVD_ADDRESS_GROUP ""

add_interface_port msip msip irq Input 1


# 
# connection point mtip
# 
add_interface mtip conduit end
set_interface_property mtip associatedClock clock
set_interface_property mtip associatedReset ""
set_interface_property mtip ENABLED true
set_interface_property mtip EXPORT_OF ""
set_interface_property mtip PORT_NAME_MAP ""
set_interface_property mtip CMSIS_SVD_VARIABLES ""
set_interface_property mtip SVD_ADDRESS_GROUP ""

add_interface_port mtip mtip irq Input 1


# 
# connection point pc
# 
add_interface pc conduit end
set_interface_property pc associatedClock clock
set_interface_property pc associatedReset ""
set_interface_property pc ENABLED true
set_interface_property pc EXPORT_OF ""
set_interface_property pc PORT_NAME_MAP ""
set_interface_property pc CMSIS_SVD_VARIABLES ""
set_interface_property pc SVD_ADDRESS_GROUP ""

add_interface_port pc pc export Output 32


# 
# connection point pc_valid
# 
add_interface pc_valid conduit end
set_interface_property pc_valid associatedClock clock
set_interface_property pc_valid associatedReset ""
set_interface_property pc_valid ENABLED true
set_interface_property pc_valid EXPORT_OF ""
set_interface_property pc_valid PORT_NAME_MAP ""
set_interface_property pc_valid CMSIS_SVD_VARIABLES ""
set_interface_property pc_valid SVD_ADDRESS_GROUP ""

add_interface_port pc_valid pc_valid export Output 1


# 
# connection point halt
# 
add_interface halt conduit end
set_interface_property halt associatedClock clock
set_interface_property halt associatedReset ""
set_interface_property halt ENABLED true
set_interface_property halt EXPORT_OF ""
set_interface_property halt PORT_NAME_MAP ""
set_interface_property halt CMSIS_SVD_VARIABLES ""
set_interface_property halt SVD_ADDRESS_GROUP ""

add_interface_port halt halt export Input 1

