# TCL File Generated by Component Editor 16.1
# Sun May 28 17:31:31 GMT+03:00 2017
# DO NOT MODIFY


# 
# spi_master "spi_master" v1.0
#  2017.05.28.17:31:31
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module spi_master
# 
set_module_property DESCRIPTION ""
set_module_property NAME spi_master
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME spi_master
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL spi_master
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file spi_master.vhd VHDL PATH periph/spi_master.vhd TOP_LEVEL_FILE

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL spi_master
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file spi_master.vhd VHDL PATH periph/spi_master.vhd


# 
# parameters
# 
add_parameter DLYBS INTEGER 2
set_parameter_property DLYBS DEFAULT_VALUE 2
set_parameter_property DLYBS DISPLAY_NAME DLYBS
set_parameter_property DLYBS TYPE INTEGER
set_parameter_property DLYBS UNITS None
set_parameter_property DLYBS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DLYBS HDL_PARAMETER true
add_parameter DLYBCT INTEGER 2
set_parameter_property DLYBCT DEFAULT_VALUE 2
set_parameter_property DLYBCT DISPLAY_NAME DLYBCT
set_parameter_property DLYBCT TYPE INTEGER
set_parameter_property DLYBCT UNITS None
set_parameter_property DLYBCT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DLYBCT HDL_PARAMETER true
add_parameter DLYBCS INTEGER 2
set_parameter_property DLYBCS DEFAULT_VALUE 2
set_parameter_property DLYBCS DISPLAY_NAME DLYBCS
set_parameter_property DLYBCS TYPE INTEGER
set_parameter_property DLYBCS UNITS None
set_parameter_property DLYBCS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DLYBCS HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point s1
# 
add_interface s1 avalon end
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock clock
set_interface_property s1 associatedReset reset
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 maximumPendingWriteTransactions 0
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true
set_interface_property s1 EXPORT_OF ""
set_interface_property s1 PORT_NAME_MAP ""
set_interface_property s1 CMSIS_SVD_VARIABLES ""
set_interface_property s1 SVD_ADDRESS_GROUP ""

add_interface_port s1 avs_s1_address address Input 2
add_interface_port s1 avs_s1_writedata writedata Input 32
add_interface_port s1 avs_s1_chipselect chipselect Input 1
add_interface_port s1 avs_s1_read read Input 1
add_interface_port s1 avs_s1_write write Input 1
add_interface_port s1 avs_s1_readdata readdata Output 32
set_interface_assignment s1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point ext
# 
add_interface ext conduit end
set_interface_property ext associatedClock clock
set_interface_property ext associatedReset ""
set_interface_property ext ENABLED true
set_interface_property ext EXPORT_OF ""
set_interface_property ext PORT_NAME_MAP ""
set_interface_property ext CMSIS_SVD_VARIABLES ""
set_interface_property ext SVD_ADDRESS_GROUP ""

add_interface_port ext sck sck Output 1
add_interface_port ext miso miso Input 1
add_interface_port ext mosi mosi Output 1
add_interface_port ext ss0 ss0 Output 1
add_interface_port ext ss1 ss1 Output 1
add_interface_port ext ss2 ss2 Output 1
add_interface_port ext ss3 ss3 Output 1


# 
# connection point intr
# 
add_interface intr conduit end
set_interface_property intr associatedClock clock
set_interface_property intr associatedReset ""
set_interface_property intr ENABLED true
set_interface_property intr EXPORT_OF ""
set_interface_property intr PORT_NAME_MAP ""
set_interface_property intr CMSIS_SVD_VARIABLES ""
set_interface_property intr SVD_ADDRESS_GROUP ""

add_interface_port intr intr irq Output 1

